version = 1

[common]
synced_files = []

[[profiles]]
name = "windows terminal"
synced_files = []
packages = []

[[profiles]]
name = "system"
synced_files = []
packages = []

[[profiles]]
name = "kitty"
synced_files = []
packages = []

[[profiles]]
name = "zsh"
synced_files = []
packages = []

[[profiles]]
name = "fastfetch"
synced_files = []
packages = []
